export const { bb, tb, bt, tt } = {
  bb: [
    { register: "A0", lines: 6, position: 380 },
    { register: "B0", lines: 6, position: 360 },
    { register: "C1", lines: 5, position: 345 },
    { register: "D1", lines: 5, position: 325 },
    { register: "E1", lines: 4, position: 305 },
    { register: "F1", lines: 4, position: 280 },
    { register: "G1", lines: 3, position: 270 },
    { register: "A1", lines: 3, position: 250 },
    { register: "B1", lines: 2, position: 230 },
    { register: "C2", lines: 2, position: 205 },
    { register: "D2", lines: 1, position: 190 },
    { register: "E2", lines: 1, position: 175 },
  ],
  tb: [
    { register: "F2", lines: 6, position: 380 },
    { register: "G2", lines: 6, position: 360 },
    { register: "A2", lines: 5, position: 345 },
    { register: "B2", lines: 5, position: 325 },
    { register: "C3", lines: 4, position: 305 },
    { register: "D3", lines: 4, position: 280 },
    { register: "E3", lines: 3, position: 270 },
    { register: "F3", lines: 3, position: 250 },
    { register: "G3", lines: 2, position: 230 },
    { register: "A3", lines: 2, position: 205 },
    { register: "B3", lines: 1, position: 190 },
    { register: "C4", lines: 1, position: 175 },
  ],
  bt: [
    { register: "C4", lines: 1, position: 500 },
    { register: "D4", lines: 1, position: 480 },
    { register: "E4", lines: 2, position: 460 },
    { register: "F4", lines: 2, position: 445 },
    { register: "G4", lines: 3, position: 425 },
    { register: "A4", lines: 3, position: 405 },
    { register: "B4", lines: 4, position: 385 },
    { register: "C5", lines: 4, position: 365 },
    { register: "D5", lines: 5, position: 345 },
    { register: "E5", lines: 5, position: 330 },
  ],
  tt: [
    { register: "A5", lines: 1, position: 500 },
    { register: "B5", lines: 1, position: 480 },
    { register: "C6", lines: 2, position: 460 },
    { register: "D6", lines: 2, position: 445 },
    { register: "E6", lines: 3, position: 425 },
    { register: "F6", lines: 3, position: 405 },
    { register: "G6", lines: 4, position: 385 },
    { register: "A6", lines: 4, position: 365 },
    { register: "B6", lines: 5, position: 345 },
    { register: "C7", lines: 5, position: 330 }, //9
    { register: "D7", lines: 6, position: 310 }, //10
    { register: "E7", lines: 6, position: 295 },
    { register: "F7", lines: 7, position: 275 },
    { register: "G7", lines: 7, position: 255 },
    { register: "A7", lines: 8, position: 235 },
    { register: "B7", lines: 8, position: 215 },
    { register: "C8", lines: 9, position: 195 },
  ],
};
